// <auto-generated />
using System;
using DuslerDunyasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuslerDunyasi.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230104122057_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DuslerDunyasi.Data.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazı1",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9185),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9175)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazı2",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9212),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9211)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazı3",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9214),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9213)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazı4",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9216),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9216)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazı5",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9218),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9217)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazı6",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9220),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9219)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazı7",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9222),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9221)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazı8",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9223),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9223)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazı9",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9225),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9225)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazı10",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9227),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9227)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazı11",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9230),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9229)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazı12",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9232),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9231)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazı13",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9233),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9233)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazı14",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9235),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9235)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazı15",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9237),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9236)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazı16",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9239),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9238)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazı17",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9240),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9240)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazı18",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9242),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9242)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazı19",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9244),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9244)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazı20",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9246),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9245)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazı21",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9248),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9247)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazı22",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9249),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9249)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazı23",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9251),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9251)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazı24",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9253),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9252)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazı25",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9317),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9317)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazı26",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9320),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9320)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazı27",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9322),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9322)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazı28",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9324),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9324)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazı29",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9326),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9325)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazı30",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9328),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9327)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazı31",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9330),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9329)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazı32",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9332),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9331)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazı33",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9334),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9333)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazı34",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9336),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9335)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazı35",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9337),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9337)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazı36",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9339),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9339)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazı37",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9341),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9341)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazı38",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9343),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9343)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazı39",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9345),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9344)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazı40",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9347),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9346)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazı41",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9349),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9348)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazı42",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9351),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9350)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazı43",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9353),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9352)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazı44",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9355),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9354)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazı45",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9356),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9356)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazı46",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9358),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9358)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazı47",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9360),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9360)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazı48",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9362),
                            Icerik = "<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 20, 57, 568, DateTimeKind.Local).AddTicks(9362)
                        });
                });

            modelBuilder.Entity("DuslerDunyasi.Data.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İş Dünyam"
                        });
                });

            modelBuilder.Entity("DuslerDunyasi.Data.Gonderi", b =>
                {
                    b.HasOne("DuslerDunyasi.Data.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("DuslerDunyasi.Data.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
